// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID                 pgtype.UUID        `json:"id"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	Category           string             `json:"category"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	LocationName       string             `json:"location_name"`
	LocationAddress    pgtype.Text        `json:"location_address"`
	LocationPoint      interface{}        `json:"location_point"`
	LocationNotes      pgtype.Text        `json:"location_notes"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	DurationMinutes    int32              `json:"duration_minutes"`
	MaxParticipants    int32              `json:"max_participants"`
	PricingType        string             `json:"pricing_type"`
	PricingAmountCents int32              `json:"pricing_amount_cents"`
	PricingCurrency    string             `json:"pricing_currency"`
	SignupDeadline     pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline       pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel         string             `json:"skill_level"`
	Notes              pgtype.Text        `json:"notes"`
	Status             string             `json:"status"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Participant struct {
	ID                 pgtype.UUID        `json:"id"`
	GameID             pgtype.UUID        `json:"game_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	TeamID             pgtype.UUID        `json:"team_id"`
	Status             string             `json:"status"`
	Paid               bool               `json:"paid"`
	PaymentAmountCents pgtype.Int4        `json:"payment_amount_cents"`
	Notes              pgtype.Text        `json:"notes"`
	JoinedAt           pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Team struct {
	ID        pgtype.UUID        `json:"id"`
	GameID    pgtype.UUID        `json:"game_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
