// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchUpdateParticipantsToConfirmed(ctx context.Context, participantIds []pgtype.UUID) error
	BatchUpdateParticipantsToWaitlist(ctx context.Context, participantIds []pgtype.UUID) error
	CancelGame(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	CountConfirmedParticipants(ctx context.Context, gameID pgtype.UUID) (int64, error)
	CountWaitlistParticipants(ctx context.Context, gameID pgtype.UUID) (int64, error)
	// Game queries
	CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error)
	// Refresh token queries
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	DeleteParticipant(ctx context.Context, id pgtype.UUID) error
	DeleteTeam(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetGame(ctx context.Context, id pgtype.UUID) (GetGameRow, error)
	GetGameForUpdate(ctx context.Context, id pgtype.UUID) (GetGameForUpdateRow, error)
	GetParticipant(ctx context.Context, id pgtype.UUID) (Participant, error)
	GetParticipantByGameAndUser(ctx context.Context, arg GetParticipantByGameAndUserParams) (Participant, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTeam(ctx context.Context, id pgtype.UUID) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListActiveParticipantsByGame(ctx context.Context, gameID pgtype.UUID) ([]ListActiveParticipantsByGameRow, error)
	ListGamesInRadius(ctx context.Context, arg ListGamesInRadiusParams) ([]ListGamesInRadiusRow, error)
	ListParticipantsByGame(ctx context.Context, gameID pgtype.UUID) ([]ListParticipantsByGameRow, error)
	ListParticipantsByGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListParticipantsByGamesRow, error)
	ListParticipantsByUser(ctx context.Context, userID pgtype.UUID) ([]Participant, error)
	ListTeamsByGame(ctx context.Context, gameID pgtype.UUID) ([]Team, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateGame(ctx context.Context, arg UpdateGameParams) (pgtype.UUID, error)
	UpdateParticipantPayment(ctx context.Context, arg UpdateParticipantPaymentParams) (Participant, error)
	UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (Participant, error)
	UpdateParticipantStatusResetJoinedAt(ctx context.Context, arg UpdateParticipantStatusResetJoinedAtParams) (Participant, error)
	UpdateParticipantTeam(ctx context.Context, arg UpdateParticipantTeamParams) (Participant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
