// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateParticipantsToConfirmed = `-- name: BatchUpdateParticipantsToConfirmed :exec
UPDATE participants
SET
    status = 'confirmed',
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BatchUpdateParticipantsToConfirmed(ctx context.Context, participantIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, batchUpdateParticipantsToConfirmed, participantIds)
	return err
}

const batchUpdateParticipantsToWaitlist = `-- name: BatchUpdateParticipantsToWaitlist :exec
UPDATE participants
SET
    status = 'waitlist',
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BatchUpdateParticipantsToWaitlist(ctx context.Context, participantIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, batchUpdateParticipantsToWaitlist, participantIds)
	return err
}

const cancelGame = `-- name: CancelGame :one
UPDATE games
SET
    status = 'cancelled',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id
`

func (q *Queries) CancelGame(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelGame, id)
	err := row.Scan(&id)
	return id, err
}

const countConfirmedParticipants = `-- name: CountConfirmedParticipants :one
SELECT COUNT(*) FROM participants
WHERE game_id = $1 AND status = 'confirmed'
`

func (q *Queries) CountConfirmedParticipants(ctx context.Context, gameID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConfirmedParticipants, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitlistParticipants = `-- name: CountWaitlistParticipants :one
SELECT COUNT(*) FROM participants
WHERE game_id = $1 AND status = 'waitlist'
`

func (q *Queries) CountWaitlistParticipants(ctx context.Context, gameID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistParticipants, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (
    owner_id,
    category,
    title,
    description,
    location_name,
    location_address,
    location_point,
    location_notes,
    start_time,
    duration_minutes,
    max_participants,
    pricing_type,
    pricing_amount_cents,
    pricing_currency,
    signup_deadline,
    drop_deadline,
    skill_level,
    notes,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
)
RETURNING id, owner_id, category, title, description, location_name, location_address,
    ST_Y(location_point::geometry) as latitude, ST_X(location_point::geometry) as longitude,
    location_notes, start_time, duration_minutes, max_participants,
    0 as current_participants, 0 as waitlist_count,
    pricing_type, pricing_amount_cents, pricing_currency, signup_deadline,
    drop_deadline, skill_level, notes, status, cancelled_at, created_at, updated_at
`

type CreateGameParams struct {
	OwnerID            pgtype.UUID        `json:"owner_id"`
	Category           string             `json:"category"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	LocationName       string             `json:"location_name"`
	LocationAddress    pgtype.Text        `json:"location_address"`
	Longitude          float64            `json:"longitude"`
	Latitude           float64            `json:"latitude"`
	LocationNotes      pgtype.Text        `json:"location_notes"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	DurationMinutes    int32              `json:"duration_minutes"`
	MaxParticipants    int32              `json:"max_participants"`
	PricingType        string             `json:"pricing_type"`
	PricingAmountCents int32              `json:"pricing_amount_cents"`
	PricingCurrency    string             `json:"pricing_currency"`
	SignupDeadline     pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline       pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel         string             `json:"skill_level"`
	Notes              pgtype.Text        `json:"notes"`
	Status             string             `json:"status"`
}

type CreateGameRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Category            string             `json:"category"`
	Title               pgtype.Text        `json:"title"`
	Description         pgtype.Text        `json:"description"`
	LocationName        string             `json:"location_name"`
	LocationAddress     pgtype.Text        `json:"location_address"`
	Latitude            interface{}        `json:"latitude"`
	Longitude           interface{}        `json:"longitude"`
	LocationNotes       pgtype.Text        `json:"location_notes"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	DurationMinutes     int32              `json:"duration_minutes"`
	MaxParticipants     int32              `json:"max_participants"`
	CurrentParticipants int32              `json:"current_participants"`
	WaitlistCount       int32              `json:"waitlist_count"`
	PricingType         string             `json:"pricing_type"`
	PricingAmountCents  int32              `json:"pricing_amount_cents"`
	PricingCurrency     string             `json:"pricing_currency"`
	SignupDeadline      pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline        pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel          string             `json:"skill_level"`
	Notes               pgtype.Text        `json:"notes"`
	Status              string             `json:"status"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Game queries
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.OwnerID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.LocationAddress,
		arg.Longitude,
		arg.Latitude,
		arg.LocationNotes,
		arg.StartTime,
		arg.DurationMinutes,
		arg.MaxParticipants,
		arg.PricingType,
		arg.PricingAmountCents,
		arg.PricingCurrency,
		arg.SignupDeadline,
		arg.DropDeadline,
		arg.SkillLevel,
		arg.Notes,
		arg.Status,
	)
	var i CreateGameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.Latitude,
		&i.Longitude,
		&i.LocationNotes,
		&i.StartTime,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentParticipants,
		&i.WaitlistCount,
		&i.PricingType,
		&i.PricingAmountCents,
		&i.PricingCurrency,
		&i.SignupDeadline,
		&i.DropDeadline,
		&i.SkillLevel,
		&i.Notes,
		&i.Status,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (
    game_id,
    user_id,
    team_id,
    status,
    paid,
    payment_amount_cents,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at
`

type CreateParticipantParams struct {
	GameID             pgtype.UUID `json:"game_id"`
	UserID             pgtype.UUID `json:"user_id"`
	TeamID             pgtype.UUID `json:"team_id"`
	Status             string      `json:"status"`
	Paid               bool        `json:"paid"`
	PaymentAmountCents pgtype.Int4 `json:"payment_amount_cents"`
	Notes              pgtype.Text `json:"notes"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.GameID,
		arg.UserID,
		arg.TeamID,
		arg.Status,
		arg.Paid,
		arg.PaymentAmountCents,
		arg.Notes,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    game_id,
    name,
    color
) VALUES (
    $1, $2, $3
)
RETURNING id, game_id, name, color, created_at
`

type CreateTeamParams struct {
	GameID pgtype.UUID `json:"game_id"`
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.GameID, arg.Name, arg.Color)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email,
    first_name,
    last_name,
    password_hash
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, first_name, last_name, password_hash, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

// User queries
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getGame = `-- name: GetGame :one
SELECT
    g.id, g.owner_id, g.category, g.title, g.description, g.location_name, g.location_address,
    ST_Y(g.location_point::geometry) as latitude, ST_X(g.location_point::geometry) as longitude,
    g.location_notes, g.start_time, g.duration_minutes, g.max_participants,
    COALESCE(COUNT(p.id) FILTER (WHERE p.status = 'confirmed'), 0)::int as current_participants,
    COALESCE(COUNT(p.id) FILTER (WHERE p.status = 'waitlist'), 0)::int as waitlist_count,
    g.pricing_type, g.pricing_amount_cents, g.pricing_currency, g.signup_deadline,
    g.drop_deadline, g.skill_level, g.notes, g.status, g.cancelled_at, g.created_at, g.updated_at
FROM games g
LEFT JOIN participants p ON p.game_id = g.id
WHERE g.id = $1
GROUP BY g.id
`

type GetGameRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	Category            string             `json:"category"`
	Title               pgtype.Text        `json:"title"`
	Description         pgtype.Text        `json:"description"`
	LocationName        string             `json:"location_name"`
	LocationAddress     pgtype.Text        `json:"location_address"`
	Latitude            interface{}        `json:"latitude"`
	Longitude           interface{}        `json:"longitude"`
	LocationNotes       pgtype.Text        `json:"location_notes"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	DurationMinutes     int32              `json:"duration_minutes"`
	MaxParticipants     int32              `json:"max_participants"`
	CurrentParticipants int32              `json:"current_participants"`
	WaitlistCount       int32              `json:"waitlist_count"`
	PricingType         string             `json:"pricing_type"`
	PricingAmountCents  int32              `json:"pricing_amount_cents"`
	PricingCurrency     string             `json:"pricing_currency"`
	SignupDeadline      pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline        pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel          string             `json:"skill_level"`
	Notes               pgtype.Text        `json:"notes"`
	Status              string             `json:"status"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (GetGameRow, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.Latitude,
		&i.Longitude,
		&i.LocationNotes,
		&i.StartTime,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentParticipants,
		&i.WaitlistCount,
		&i.PricingType,
		&i.PricingAmountCents,
		&i.PricingCurrency,
		&i.SignupDeadline,
		&i.DropDeadline,
		&i.SkillLevel,
		&i.Notes,
		&i.Status,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameForUpdate = `-- name: GetGameForUpdate :one
SELECT
    id, owner_id, category, title, description, location_name, location_address,
    ST_Y(location_point::geometry) as latitude, ST_X(location_point::geometry) as longitude,
    location_notes, start_time, duration_minutes, max_participants,
    pricing_type, pricing_amount_cents, pricing_currency, signup_deadline,
    drop_deadline, skill_level, notes, status, cancelled_at, created_at, updated_at
FROM games
WHERE id = $1
FOR UPDATE
`

type GetGameForUpdateRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OwnerID            pgtype.UUID        `json:"owner_id"`
	Category           string             `json:"category"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	LocationName       string             `json:"location_name"`
	LocationAddress    pgtype.Text        `json:"location_address"`
	Latitude           interface{}        `json:"latitude"`
	Longitude          interface{}        `json:"longitude"`
	LocationNotes      pgtype.Text        `json:"location_notes"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	DurationMinutes    int32              `json:"duration_minutes"`
	MaxParticipants    int32              `json:"max_participants"`
	PricingType        string             `json:"pricing_type"`
	PricingAmountCents int32              `json:"pricing_amount_cents"`
	PricingCurrency    string             `json:"pricing_currency"`
	SignupDeadline     pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline       pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel         string             `json:"skill_level"`
	Notes              pgtype.Text        `json:"notes"`
	Status             string             `json:"status"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetGameForUpdate(ctx context.Context, id pgtype.UUID) (GetGameForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getGameForUpdate, id)
	var i GetGameForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.Latitude,
		&i.Longitude,
		&i.LocationNotes,
		&i.StartTime,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.PricingType,
		&i.PricingAmountCents,
		&i.PricingCurrency,
		&i.SignupDeadline,
		&i.DropDeadline,
		&i.SkillLevel,
		&i.Notes,
		&i.Status,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at FROM participants
WHERE id = $1
`

func (q *Queries) GetParticipant(ctx context.Context, id pgtype.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByGameAndUser = `-- name: GetParticipantByGameAndUser :one
SELECT id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at FROM participants
WHERE game_id = $1 AND user_id = $2
`

type GetParticipantByGameAndUserParams struct {
	GameID pgtype.UUID `json:"game_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParticipantByGameAndUser(ctx context.Context, arg GetParticipantByGameAndUserParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByGameAndUser, arg.GameID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, game_id, name, color, created_at FROM teams
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, password_hash, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, password_hash, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listGamesInRadius = `-- name: ListGamesInRadius :many
SELECT
    g.id, g.owner_id, g.category, g.title, g.description, g.location_name, g.location_address,
    ST_Y(g.location_point::geometry) as latitude, ST_X(g.location_point::geometry) as longitude,
    g.location_notes, g.start_time, g.duration_minutes, g.max_participants,
    COALESCE(COUNT(p.id) FILTER (WHERE p.status = 'confirmed'), 0)::int as current_participants,
    g.pricing_type, g.pricing_amount_cents, g.pricing_currency, g.signup_deadline,
    g.drop_deadline, g.skill_level, g.notes, g.status, g.cancelled_at, g.created_at, g.updated_at,
    up.status as user_participation_status
FROM games g
LEFT JOIN participants p ON p.game_id = g.id AND p.status = 'confirmed'
LEFT JOIN participants up ON up.game_id = g.id AND up.user_id = $1
WHERE ST_DWithin(
    g.location_point,
    ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography,
    $4::float8
)
AND g.start_time >= $5
AND ($6::timestamptz IS NULL OR g.start_time <= $6)
AND ($7::varchar IS NULL OR g.status = $7)
AND g.category = ANY($8::varchar[])
GROUP BY g.id, up.user_id, up.status
ORDER BY g.start_time ASC
LIMIT $10 OFFSET $9
`

type ListGamesInRadiusParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Longitude  float64            `json:"longitude"`
	Latitude   float64            `json:"latitude"`
	Radius     float64            `json:"radius"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Status     pgtype.Text        `json:"status"`
	Categories []string           `json:"categories"`
	Offset     int32              `json:"offset"`
	Limit      int32              `json:"limit"`
}

type ListGamesInRadiusRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OwnerID                 pgtype.UUID        `json:"owner_id"`
	Category                string             `json:"category"`
	Title                   pgtype.Text        `json:"title"`
	Description             pgtype.Text        `json:"description"`
	LocationName            string             `json:"location_name"`
	LocationAddress         pgtype.Text        `json:"location_address"`
	Latitude                interface{}        `json:"latitude"`
	Longitude               interface{}        `json:"longitude"`
	LocationNotes           pgtype.Text        `json:"location_notes"`
	StartTime               pgtype.Timestamptz `json:"start_time"`
	DurationMinutes         int32              `json:"duration_minutes"`
	MaxParticipants         int32              `json:"max_participants"`
	CurrentParticipants     int32              `json:"current_participants"`
	PricingType             string             `json:"pricing_type"`
	PricingAmountCents      int32              `json:"pricing_amount_cents"`
	PricingCurrency         string             `json:"pricing_currency"`
	SignupDeadline          pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline            pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel              string             `json:"skill_level"`
	Notes                   pgtype.Text        `json:"notes"`
	Status                  string             `json:"status"`
	CancelledAt             pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UserParticipationStatus pgtype.Text        `json:"user_participation_status"`
}

func (q *Queries) ListGamesInRadius(ctx context.Context, arg ListGamesInRadiusParams) ([]ListGamesInRadiusRow, error) {
	rows, err := q.db.Query(ctx, listGamesInRadius,
		arg.UserID,
		arg.Longitude,
		arg.Latitude,
		arg.Radius,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Categories,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesInRadiusRow{}
	for rows.Next() {
		var i ListGamesInRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.LocationAddress,
			&i.Latitude,
			&i.Longitude,
			&i.LocationNotes,
			&i.StartTime,
			&i.DurationMinutes,
			&i.MaxParticipants,
			&i.CurrentParticipants,
			&i.PricingType,
			&i.PricingAmountCents,
			&i.PricingCurrency,
			&i.SignupDeadline,
			&i.DropDeadline,
			&i.SkillLevel,
			&i.Notes,
			&i.Status,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserParticipationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByGame = `-- name: ListParticipantsByGame :many
SELECT
    p.id,
    p.game_id,
    p.user_id,
    p.team_id,
    p.status,
    p.paid,
    p.payment_amount_cents,
    p.notes,
    p.joined_at,
    p.updated_at,
    u.email,
    u.first_name,
    u.last_name
FROM participants p
INNER JOIN users u ON p.user_id = u.id
WHERE p.game_id = $1
ORDER BY p.joined_at ASC
`

type ListParticipantsByGameRow struct {
	ID                 pgtype.UUID        `json:"id"`
	GameID             pgtype.UUID        `json:"game_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	TeamID             pgtype.UUID        `json:"team_id"`
	Status             string             `json:"status"`
	Paid               bool               `json:"paid"`
	PaymentAmountCents pgtype.Int4        `json:"payment_amount_cents"`
	Notes              pgtype.Text        `json:"notes"`
	JoinedAt           pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Email              string             `json:"email"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
}

func (q *Queries) ListParticipantsByGame(ctx context.Context, gameID pgtype.UUID) ([]ListParticipantsByGameRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsByGameRow{}
	for rows.Next() {
		var i ListParticipantsByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.Paid,
			&i.PaymentAmountCents,
			&i.Notes,
			&i.JoinedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByGames = `-- name: ListParticipantsByGames :many
SELECT
    p.id,
    p.game_id,
    p.user_id,
    p.team_id,
    p.status,
    p.paid,
    p.payment_amount_cents,
    p.notes,
    p.joined_at,
    p.updated_at,
    u.email,
    u.first_name,
    u.last_name
FROM participants p
INNER JOIN users u ON p.user_id = u.id
WHERE p.game_id = ANY($1::uuid[])
ORDER BY p.game_id, p.joined_at ASC
`

type ListParticipantsByGamesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	GameID             pgtype.UUID        `json:"game_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	TeamID             pgtype.UUID        `json:"team_id"`
	Status             string             `json:"status"`
	Paid               bool               `json:"paid"`
	PaymentAmountCents pgtype.Int4        `json:"payment_amount_cents"`
	Notes              pgtype.Text        `json:"notes"`
	JoinedAt           pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Email              string             `json:"email"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
}

func (q *Queries) ListParticipantsByGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListParticipantsByGamesRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsByGames, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsByGamesRow{}
	for rows.Next() {
		var i ListParticipantsByGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.Paid,
			&i.PaymentAmountCents,
			&i.Notes,
			&i.JoinedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByUser = `-- name: ListParticipantsByUser :many
SELECT id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at FROM participants
WHERE user_id = $1
ORDER BY joined_at DESC
`

func (q *Queries) ListParticipantsByUser(ctx context.Context, userID pgtype.UUID) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.TeamID,
			&i.Status,
			&i.Paid,
			&i.PaymentAmountCents,
			&i.Notes,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByGame = `-- name: ListTeamsByGame :many
SELECT id, game_id, name, color, created_at FROM teams
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTeamsByGame(ctx context.Context, gameID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    location_name = COALESCE($3, location_name),
    location_address = COALESCE($4, location_address),
    location_point = CASE
        WHEN $5::float8 IS NOT NULL
            AND $6::float8 IS NOT NULL
        THEN ST_SetSRID(ST_MakePoint($5, $6), 4326)::geography
        ELSE location_point
    END,
    location_notes = COALESCE($7, location_notes),
    start_time = COALESCE($8, start_time),
    duration_minutes = COALESCE($9, duration_minutes),
    max_participants = COALESCE($10, max_participants),
    pricing_type = COALESCE($11, pricing_type),
    pricing_amount_cents = COALESCE($12, pricing_amount_cents),
    pricing_currency = COALESCE($13, pricing_currency),
    signup_deadline = COALESCE($14, signup_deadline),
    drop_deadline = COALESCE($15, drop_deadline),
    skill_level = COALESCE($16, skill_level),
    notes = COALESCE($17, notes),
    status = COALESCE($18, status),
    updated_at = NOW()
WHERE id = $19
RETURNING id
`

type UpdateGameParams struct {
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	LocationName       pgtype.Text        `json:"location_name"`
	LocationAddress    pgtype.Text        `json:"location_address"`
	LocationLongitude  pgtype.Float8      `json:"location_longitude"`
	LocationLatitude   pgtype.Float8      `json:"location_latitude"`
	LocationNotes      pgtype.Text        `json:"location_notes"`
	StartTime          pgtype.Timestamptz `json:"start_time"`
	DurationMinutes    pgtype.Int4        `json:"duration_minutes"`
	MaxParticipants    pgtype.Int4        `json:"max_participants"`
	PricingType        pgtype.Text        `json:"pricing_type"`
	PricingAmountCents pgtype.Int4        `json:"pricing_amount_cents"`
	PricingCurrency    pgtype.Text        `json:"pricing_currency"`
	SignupDeadline     pgtype.Timestamptz `json:"signup_deadline"`
	DropDeadline       pgtype.Timestamptz `json:"drop_deadline"`
	SkillLevel         pgtype.Text        `json:"skill_level"`
	Notes              pgtype.Text        `json:"notes"`
	Status             pgtype.Text        `json:"status"`
	ID                 pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.LocationAddress,
		arg.LocationLongitude,
		arg.LocationLatitude,
		arg.LocationNotes,
		arg.StartTime,
		arg.DurationMinutes,
		arg.MaxParticipants,
		arg.PricingType,
		arg.PricingAmountCents,
		arg.PricingCurrency,
		arg.SignupDeadline,
		arg.DropDeadline,
		arg.SkillLevel,
		arg.Notes,
		arg.Status,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateParticipantPayment = `-- name: UpdateParticipantPayment :one
UPDATE participants
SET
    paid = $2,
    payment_amount_cents = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at
`

type UpdateParticipantPaymentParams struct {
	ID                 pgtype.UUID `json:"id"`
	Paid               bool        `json:"paid"`
	PaymentAmountCents pgtype.Int4 `json:"payment_amount_cents"`
}

func (q *Queries) UpdateParticipantPayment(ctx context.Context, arg UpdateParticipantPaymentParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipantPayment, arg.ID, arg.Paid, arg.PaymentAmountCents)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :one
UPDATE participants
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at
`

type UpdateParticipantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipantStatus, arg.ID, arg.Status)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantStatusResetJoinedAt = `-- name: UpdateParticipantStatusResetJoinedAt :one
UPDATE participants
SET
    status = $2,
    updated_at = NOW(),
    joined_at = NOW()
WHERE id = $1
RETURNING id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at
`

type UpdateParticipantStatusResetJoinedAtParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateParticipantStatusResetJoinedAt(ctx context.Context, arg UpdateParticipantStatusResetJoinedAtParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipantStatusResetJoinedAt, arg.ID, arg.Status)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantTeam = `-- name: UpdateParticipantTeam :one
UPDATE participants
SET
    team_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, user_id, team_id, status, paid, payment_amount_cents, notes, joined_at, updated_at
`

type UpdateParticipantTeamParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateParticipantTeam(ctx context.Context, arg UpdateParticipantTeamParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipantTeam, arg.ID, arg.TeamID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.TeamID,
		&i.Status,
		&i.Paid,
		&i.PaymentAmountCents,
		&i.Notes,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email)
WHERE id = $4
RETURNING id, email, first_name, last_name, password_hash, created_at
`

type UpdateUserParams struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
