// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIFaceTest creates a new instance of IFaceTest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFaceTest(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFaceTest {
	mock := &IFaceTest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IFaceTest is an autogenerated mock type for the IFaceTest type
type IFaceTest struct {
	mock.Mock
}

type IFaceTest_Expecter struct {
	mock *mock.Mock
}

func (_m *IFaceTest) EXPECT() *IFaceTest_Expecter {
	return &IFaceTest_Expecter{mock: &_m.Mock}
}

// Test provides a mock function for the type IFaceTest
func (_mock *IFaceTest) Test() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IFaceTest_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type IFaceTest_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
func (_e *IFaceTest_Expecter) Test() *IFaceTest_Test_Call {
	return &IFaceTest_Test_Call{Call: _e.mock.On("Test")}
}

func (_c *IFaceTest_Test_Call) Run(run func()) *IFaceTest_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IFaceTest_Test_Call) Return(err error) *IFaceTest_Test_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IFaceTest_Test_Call) RunAndReturn(run func() error) *IFaceTest_Test_Call {
	_c.Call.Return(run)
	return _c
}
